
package aulaac1;

//exercicio 3 da aula introdução a POO

public class Exercicio3POO {
    
         // classe 1
         public class Cliente{
        
        
         //atributos 1
         private String nome;
         private String endereco;
         private String cidade;
         private String UF;
         private int CEP;
        
        
          //criando metodo 1
         public void IncluirNovoCliente(){ 
         }
          public void AtualizarCliente(){
         }
          
           
          
           // classe 2
           public class PessoaJuridica{
        
        
           //atributos 2
           private int CNPJ;
           private String incricaoestadual;
           private String razaosocial;
    
            //criando metodo 2
            public void ValidadeCNPJ(){
           
           }
        
            // classe 3
            public class PessoaFisica {
            
            
            // atributos 3
            private int CPF;
            private int RG;
            private char Sexo;
            private Date datadenascimento;
            
       
            // criando metodo 3
            
              public void ValidarCPF(){
                  
             }
            
            
            
        
        }            
      }   
    }
  }
